TARGET = bin/main

INCDIR = ./include/
CFLAGS = -Wall -O2 -std=c11

LIBS = -lSDL2 -lm

all:
	@mkdir -p bin
	gcc src/main.c -o $(TARGET) $(addprefix -I,$(INCDIR)) $(CFLAGS) $(LIBS)

clean:
	rm -rf bin
