name: Build test
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev git
        sudo apt-get install -y g++ build-essential autoconf automake cmake doxygen bison flex libncurses5-dev libsdl1.2-dev libreadline-dev libusb-dev texinfo libgmp3-dev libmpfr-dev libelf-dev libmpc-dev libfreetype6-dev zlib1g-dev libtool libtool-bin subversion git tcl unzip wget
        git clone https://github.com/pspdev/psptoolchain.git && cd psptoolchain && sudo ./toolchain-sudo.sh && cd
        git clone https://github.com/pspdev/pspsdk.git && cd pspsdk && ./configure && make && make install && cd
    - name: make linux
      run: make linux
    - name: make psp
      run: make psp
