name: Build test
on:
  push:
    branches: 
      - master

jobs:
  check:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install cppcheck
      - name: Check code
        run: cppcheck --enable=all --force src/

  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: make linux

  build_psp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install psptoolchain
      run: |
        git clone https://github.com/pspdev/psptoolchain
        cd psptoolchain
        sudo apt-get update -y -qq
        sudo apt-get install -y g++ build-essential autoconf automake cmake doxygen bison flex libncurses5-dev libsdl1.2-dev libreadline-dev libusb-dev texinfo libgmp3-dev libmpfr-dev libelf-dev libmpc-dev libfreetype6-dev zlib1g-dev libtool libtool-bin subversion git tcl unzip wget
        sudo ./toolchain-sudo.sh
        whereis psp-ranlib
        whereis psp-gcc
        echo $PATH
        echo ::set-env name=PATH::$PATH:/usr/local/pspdev/bin
    - name: Install pspsdk
      run: |
        git clone https://github.com/pspdev/pspsdk
        cd pspsdk
        ./bootstrap
        mkdir -p build-psp && pushd build-psp
        ../configure --with-pspdev=/usr/local --target=psp
        make
        sudo make install
        echo ::set-env name=PATH::$PATH:/usr/local/pspdev/bin:/usr/local/psp/sdk/bin
    - name: Compile
      run: make psp
