name: Build test
on:
  push:
    branches: 
      - master

jobs:
  check:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install cppcheck
      - name: Check code
        run: make check

  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: make linux
